FROM python:3.12

ENV JENKINS_URL=http://your-jenkins-url
ENV JENKINS_USER=your-username
ENV JENKINS_API_TOKEN=${JENKINS_API_TOKEN}
ENV GERRIT_API_KEY=${GERRIT_API_KEY}
ENV GERRIT_BASE_URL="https://gerrit.eng.nutanix.com"
ENV SLACK_BOT_TOKEN=${SLACK_BOT_TOKEN}
ENV JIRA_API_TOKEN=${JIRA_API_TOKEN}    